repositories:
  - name: ".github"
    stage: allianz
  - name: "ospo"
    stage: allianz
  - name: "new-project"
    stage: allianz-incubator
  - name: "ng-aquila"
    stage: allianz
  - name: "calculus-prime-pnc"
    stage: allianz
  - name: "gem-config"
    stage: allianz
  - name: "license-scout"
    stage: allianz
  - name: "merge-bot"
    stage: allianz
  - name: "merge-bot-config"
    stage: allianz
  - name: "merge-processor"
    stage: allianz
  - name: "test-permissions"
    stage: allianz-incubator
 
  - name: "playground"
    stage: allianz-incubator